server:
   port: 8080
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/CRUDTest?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
 